server:
  port: 8070

spring:
  application:
    name: call-report-service

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=call_logs_schema
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: false

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka